version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: scripts/stopscript.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deletescript.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startscript.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stopscript.sh
      timeout: 300
      runas: root
