version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/carreerladder2/build
hooks:
  BeforeInstall:
    - location: scripts/stopscript.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/deletescript.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/startscript.sh
      timeout: 3600
      runas: root
